services:
  tests:
    image: golang:1.25-alpine3.22
    depends_on:
      - postgres
    volumes:
      - type: bind
        source: ./
        target: /src
    working_dir: /src

  postgres:
    image: postgres:18-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "app" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

volumes:
  postgres:
